# Use uma imagem base oficial do Python
FROM python:3.12

# Defina o diretório de trabalho dentro do container
WORKDIR /app

# Copie o arquivo requirements.txt para o container
COPY requirements.txt .

# Instale as dependências do Python
RUN pip install --no-cache-dir -r requirements.txt

# Copie o restante dos arquivos do seu projeto para o container
COPY . .

# Defina o comando padrão para executar seu script
CMD ["python", "csv_to_json/script.py"]
